language: node_js
node_js:
- node
env:
- CXX=g++-5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
  packages:
  - g++-5
  - zip
install:
- npm i -g yarn && yarn
script:
- yarn build
before_deploy:
- zip -r dists.zip dist/
deploy:
  provider: releases
  api_key:
    secure: jIozqRvQAzfIXMMQnTZFlmucgMikHpeY08Vu8GBZ8WlZGhSHjZqZHNzd35I0HM/NHBkx8py6IRGXakcxGJIGy2gD2UK5N4aGIVyM4RT7lyNPGn7ffd68+KmZV60HEwW+IqApI9duDgal7oKffVFY9p7VMgjrXzX/a1Ey8DM8/agX2u4TSU5UvoOmtWwbAmhS+ZKKUu06mW8s6nLNtZuVJ6y8XibLfQNLJVVQH6DypVt6JHOSU57RKoyr369yHu4DEGNVFTr5f0JET5f3vRI1Ni2SGL5+sscu26iMOZWKSMsmmkLAPwV557srC8rGFh0Qta715LpXfbamYlZSZSfjofQqcbgFV4loIE7dyEm8lwWRC1Yb4/jUiKQxQqFVCCGaksXFkqeI7vp9MMvE1lFMnx5nn10RsbiqBqf54yfF6H70NGV1gBZCt+AT8+1KrIbFiFAzS5MsPw+YxKJfbfc2k8vicEsyGl1bkDpfwnKryJGyay+c+e5UkbsVjD7r6G/HUlV2kJ/iPncMNuW8iGhgD2GyylDFsFJAnkMfuq4e7RnL1tig2lv3ZJeDu3I0qCGrJZoX/aliQjnJOwJUiZYb7H9TPdjgVmYaFSE1LTrBe4Wth5V0zt36hVXZ1kuK3lO0Jl7yq3urzo+G/RM6HuByxwz4+68ULSUpHwQ5H1X+lNE=
  file: dists.zip
  on:
    repo: sjtug/sjtug-mirror-frontend
    branch: v2
